version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  # REDIS: used for "Hot" data caching (Live game state, current turn, bidding)
  # This is memory-based and extremely fast for real-time play.
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # MONGO: used for "Cold" data storage (User accounts, Match history, Leaderboards)
  # This is disk-based and keeps data permanently even if the server restarts.
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Ensures player stats aren't lost on restart     
      

  
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - ./client/.env
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
