version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - ./client/.env
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
